name: sfc-convs-env
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.6
  - pytorch=1.2.0
  - torchvision=0.4.0
  - cudatoolkit=10.0
  - matplotlib=3.1.1
  - h5py=2.9.0
  - pandas=0.25.1
  - scikit-learn=0.21.3
  - tqdm=4.35.0
  - vtk=8.2.0
  - tensorflow-gpu=1.14.0
  - pip:
    - git+https://github.com/daavoo/pyntcloud
    - hilbertcurve==1.0.1